selected_ids = ['astropy__astropy-12907', 'astropy__astropy-14182', 'astropy__astropy-14365', 'astropy__astropy-14995', 'django__django-10914', 'django__django-11099', 'django__django-11133', 'django__django-11179', 'django__django-11815', 'django__django-11848', 'django__django-11964', 'django__django-11999', 'django__django-12125', 'django__django-12308', 'django__django-12708', 'django__django-13028', 'django__django-13033', 'django__django-13158', 'django__django-13315', 'django__django-13401', 'django__django-13551', 'django__django-13590', 'django__django-13658', 'django__django-13925', 'django__django-13933', 'django__django-13964', 'django__django-14017', 'django__django-14155', 'django__django-14238', 'django__django-14534', 'django__django-14580', 'django__django-14608', 'django__django-14672', 'django__django-14752', 'django__django-14787', 'django__django-14855', 'django__django-14915', 'django__django-14999', 'django__django-15252', 'django__django-15695', 'django__django-15814', 'django__django-15851', 'django__django-16139', 'django__django-16255', 'django__django-16527', 'django__django-16595', 'django__django-17087', 'matplotlib__matplotlib-23299', 'matplotlib__matplotlib-23314', 'matplotlib__matplotlib-23476', 'matplotlib__matplotlib-24149', 'matplotlib__matplotlib-24970', 'matplotlib__matplotlib-25311', 'matplotlib__matplotlib-25332', 'psf__requests-2317', 'pydata__xarray-4094', 'pylint-dev__pylint-7080', 'pytest-dev__pytest-7432', 'pytest-dev__pytest-7490']

Long:
Thức giấc mỗi ngày là khi màn đêm vừa kéo về
Tiếng chuông ngân dài, nhưng vẫn không thấy một ai
Bờ vai như rã rời, con tim em muốn dừng lại thôi
Kết thúc câu chuyện cũng là lúc không ai bước tiếp

Lam:
Em giờ đã có bầu trời mới, mọi chuyện sẽ qua thôi
Anh thì tìm kiếm tình yêu dù đánh mất lâu rồi
Chạy thật nhanh, đi thật xa để cố quên những gì xảy ra
Nhưng trước mắt anh vẫn toàn thấy ký ức về em
Em giờ đã có bầu trời mới, thế giới cũng đổi thay
Giữa muôn vàn vì sao chiếu sáng nơi đây chỉ có mỗi anh lạc lõng
Đoạn đường mới đừng tìm lại giấc mơ em đã cất sâu
Có khi ngày mai ta sẽ vô tình gặp nhau, đứng thật lâu

Thỏ:
Cứ mỗi sớm ban mai là giấc mơ xưa lại đến
Vẫn cứ ngỡ bên tai là những thanh âm ngọt ngào
Gió cuốn những đám mây về một nơi xa
Một bầu trời đầy rạng ngời nhưng thiếu vắng đôi ta
Con đường kia chỉ một mình anh thôi
Em giờ đang bước nơi xa cùng người
Những nụ cười đó từng được dành cho anh
Chỉ còn nhạt nhoà trong những cơn mơ

Lam:
Em giờ đã có bầu trời mới, mọi chuyện sẽ qua thôi
Anh thì tìm kiếm tình yêu dù đánh mất lâu rồi
Chạy thật nhanh, đi thật xa để cố quên những gì xảy ra
Nhưng trước mắt anh vẫn toàn thấy ký ức về em
Em giờ đã có bầu trời mới, thế giới cũng đổi thay
Giữa muôn vàn vì sao chiếu sáng nơi đây chỉ có mỗi anh lạc lõng
Đoạn đường mới đừng tìm lại giấc mơ em đã cất sâu
Có khi ngày mai ta sẽ vô tình gặp nhau, đứng thật lâu

Cào:
Ai đưa tay như đang níu lấy hoa phai đang rơi
Chuyện tình buồn quên rồi trong sương đêm sang mai, ai mang phơi
Sao vang nghe bên tai âm thanh như ai đang kêu tên ai
Ngỡ như anh vẫn còn cảm thấy hơi thở của em sau vai
Em ngọt ngào nhưng lại làm anh mất ngủ như một ly nâu
Lồng ngực cháy bỏng vì em mỗi khi anh lại hít một hơi sâu
Bản nhạc ngày đó ta nghe Thanh Bùi hát mãi Tình Về Nơi Đâu 2014 nhìn vào mắt em anh nghĩ mình sẽ trọn đời bên nhau
Người mơ sông núi người mơ bầu trời chỉ có mình anh là muốn cạnh em trọn đời anh đã không biết mà cứ bước tiếp đến khi anh thấy bàn chân rệu rời là lúc anh biết nhịp đập của con tim anh đang sai
Anh biết đến lúc dừng lại mong em hạnh phúc khi đi bên ai
Hoà mình vào dòng người để không ai thấy được mình cô đơn
Đôi lúc anh nở nụ cười lại thấy sâu thẳm trong mình đau hơn
Anh đưa mắt lên tự hỏi đâu đó bên dưới bầu trời xanh dương em đã tìm thấy cho mình những điều em mong hay vẫn chưa bước qua tháng ngày mưa tuôn

Thơm:
Vậy khung trời anh liệu có thể
Quay trở lại như xưa
Mình anh ở trong một thế giới
Chẳng thể như lúc đầu
Nơi mặt trời cứ mãi bâng khuâng giữa đêm với ngày
Nơi nụ hoa, nhành cỏ xanh cánh bướm cứ phân vân

Lam:
Em giờ đã có bầu trời mới, thế giới cũng đổi thay
Giữa muôn vàn vì sao chiếu sáng nơi đây chỉ có mỗi anh lạc lõng
Đoạn đường mới đừng tìm lại giấc mơ em đã cất sâu
Có khi ngày mai ta sẽ vô tình gặp nhau, cúi chào nhau
